#!/usr/bin/env python3
"""
OAuth Setup Helper for Commons Depicts Analyzer

This script helps you set up OAuth configuration step-by-step.
"""

import os
import secrets
from pathlib import Path

def main():
    print("=" * 70)
    print("  Commons Depicts Analyzer - OAuth Setup Helper")
    print("=" * 70)
    print()
    
    env_path = Path(__file__).parent / '.env'
    
    if env_path.exists():
        print(f"⚠️  .env file already exists at: {env_path}")
        response = input("Do you want to overwrite it? (y/N): ").strip().lower()
        if response != 'y':
            print("Aborting setup. Your existing .env file was not modified.")
            return
        print()
    
    print("Step 1: Register an OAuth Application")
    print("-" * 70)
    print("1. Visit: https://meta.wikimedia.org/wiki/Special:OAuthConsumerRegistration/propose/oauth2")
    print("2. Fill in the form:")
    print("   - Application name: Commons Depicts Analyzer (Development)")
    print("   - Description: Tool for analyzing depicts statements")
    print("   - Callback URL: http://localhost:5000/auth/callback")
    print("   - Grants: Check 'Basic rights' and 'Edit structured data'")
    print("3. Submit and copy your Client ID and Client Secret")
    print()
    
    client_id = input("Enter your OAuth Client ID: ").strip()
    if not client_id:
        print("❌ Client ID cannot be empty!")
        return
    
    client_secret = input("Enter your OAuth Client Secret: ").strip()
    if not client_secret:
        print("❌ Client Secret cannot be empty!")
        return
    
    print()
    print("Step 2: Generate Flask Secret Key")
    print("-" * 70)
    flask_secret = secrets.token_hex(32)
    print(f"✓ Generated secure secret key: {flask_secret[:16]}...{flask_secret[-8:]}")
    print()
    
    print("Step 3: Writing .env file")
    print("-" * 70)
    
    env_content = f"""# Commons Depicts Analyzer - OAuth Configuration
# Generated by setup_oauth.py
# NEVER commit this file to version control!

# OAuth 2.0 Credentials
OAUTH_CLIENT_ID={client_id}
OAUTH_CLIENT_SECRET={client_secret}
OAUTH_CALLBACK_URL=http://localhost:5000/auth/callback

# Flask Secret Key
FLASK_SECRET_KEY={flask_secret}

# Environment
ENVIRONMENT=development

# Optional: Uncomment to customize
# SESSION_LIFETIME_MINUTES=60
# HOST=127.0.0.1
# PORT=5000
# DEBUG=true
"""
    
    with open(env_path, 'w') as f:
        f.write(env_content)
    
    print(f"✓ Created .env file at: {env_path}")
    print()
    print("=" * 70)
    print("✅ OAuth setup complete!")
    print("=" * 70)
    print()
    print("Next steps:")
    print("1. Install dependencies: pip install -r requirements.txt")
    print("2. Run the application: python backend/main.py")
    print("3. Open http://localhost:5000 in your browser")
    print("4. Click 'Login' to test the OAuth flow")
    print()
    print("⚠️  SECURITY REMINDER:")
    print("   - Never commit your .env file to git")
    print("   - Keep your Client Secret secure")
    print("   - Rotate keys if they are ever exposed")
    print()

if __name__ == "__main__":
    main()
